version: '3.8'

services:
  # PostgreSQL for Price Service
  pricedb:
    image: postgres:14.5
    environment:
      POSTGRES_DB: pricedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ab123456
    ports:
      - "5435:5432"  # Host Port: Container Port
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pricedb-data:/var/lib/postgresql/data
    restart: unless-stopped

  # PostgreSQL for User Service
  userdb:
    image: postgres:14.5
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ab123456
    ports:
      - "5436:5432"  # Host Port: Container Port
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - userdb-data:/var/lib/postgresql/data
    restart: unless-stopped

  # PostgreSQL for Wallet Service
  walletdb:
    image: postgres:14.5
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ab123456
    ports:
      - "5434:5432"  # Host Port: Container Port
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - walletdb-data:/var/lib/postgresql/data
    restart: unless-stopped

  # PostgreSQL for Outbox Service
  outboxdb:
    image: postgres:14.5
    environment:
      POSTGRES_DB: outboxdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ab123456
    ports:
      - "5437:5432"  # Host Port: Container Port
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - outboxdb-data:/var/lib/postgresql/data
    restart: unless-stopped

  # PostgreSQL for Transaction Service
  transactiondb:
    image: postgres:14.5
    environment:
      POSTGRES_DB: transactiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ab123456
    ports:
      - "5438:5432"  # Host Port: Container Port
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - transactiondb-data:/var/lib/postgresql/data
    restart: unless-stopped

  # Common Redis Service
  redis:
    image: redis:7.0
    command: ["redis-server", "--requirepass", "Ab123456"]
    ports:
      - "6379:6379"
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Ab123456", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-data:/data
    restart: unless-stopped

  # Common RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"      # Main RabbitMQ port
      - "15672:15672"    # RabbitMQ management interface
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: unless-stopped

  # Price Service
  price-service:
    build:
      context: ./price-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pricedb:5432/pricedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ab123456
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: Ab123456
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      pricedb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - microservice-network
    restart: unless-stopped

  # Auth Service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      USER_SERVICE_URL: http://user-service:8081
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: Ab123456
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - microservice-network
    restart: unless-stopped

  # User Service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      AUTH_SERVICE_URL: http://auth-service:8084
      SPRING_DATASOURCE_URL: jdbc:postgresql://userdb:5432/userdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ab123456
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      userdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - microservice-network
    restart: unless-stopped

  # Wallet Service
  wallet-service:
    build:
      context: ./wallet-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://walletdb:5432/walletdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ab123456
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: Ab123456
      SPRING_DATA_REDIS_TIMEOUT: 60000ms
    depends_on:
      walletdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - microservice-network
    restart: unless-stopped

  # Outbox Service
  outbox-service:
    build:
      context: ./outbox-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://outboxdb:5432/outboxdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ab123456
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: Ab123456
    depends_on:
      outboxdb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - microservice-network
    restart: unless-stopped

  # Transaction Service
  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://transactiondb:5432/transactiondb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Ab123456
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: Ab123456
      SPRING_DATA_REDIS_TIMEOUT: 60000ms
    depends_on:
      transactiondb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - microservice-network
    restart: unless-stopped

networks:
  microservice-network:
    driver: bridge

volumes:
  pricedb-data:
  userdb-data:
  walletdb-data:
  outboxdb-data:
  transactiondb-data:
  redis-data:
  rabbitmq-data:
