openapi:
  title: "Transaction Service API"
  version: "v1"

spring:
  rabbitmq:
    host: rabbitmq  # RabbitMQ host in Docker environment
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://db:5432/transactiondb  # Docker database connection
    username: postgres
    password: Ab123456
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false  # Disable open-in-view for better performance
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Explicitly specify PostgreSQL dialect

  data:
    redis:
      host: redis
      port: 6379
      password: Ab123456
      timeout: 60000ms  # 60 seconds, specified in milliseconds

# SpringDoc settings for API documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging pattern
logging:
  level:
    com.jack.transactionservice: INFO

  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"
