openapi:
  title: "User Service API"
  version: "v1"

spring:
  rabbitmq:
    host: localhost  # Local RabbitMQ
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb  # Local database connection
    username: postgres
    password: Ab123456
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false  # Disable open-in-view for better performance

  data:
    redis:
      host: localhost
      port: 6379
      password: Ab123456
      timeout: 60000ms  # 60 seconds, specified in milliseconds

# SpringDoc settings for API documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging pattern
logging:
  level:
    com.jack.userservice: INFO  # Adjust the logging level to INFO for user service

  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"
