openapi:
  title: Outbox Service API
  version: v1.0
  description: This API provides Outbox service for applications.
  termsOfService: https://test.com/terms
  contact:
    name: Jack Lee
    email: jack@test.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

spring:
  rabbitmq:
    host: rabbitmq  # RabbitMQ host in Docker environment
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://db:5432/outboxdb  # Docker database connection for outbox messages
    username: postgres
    password: Ab123456
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true  # Outbox pattern requires auto-commit for message persistence

  jpa:
    hibernate:
      ddl-auto: update  # Automatically create/update tables in the database
    show-sql: true  # For debugging, shows SQL statements in the log
    open-in-view: false  # Disable Open Session in View for better performance

# SpringDoc settings for API documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging pattern
logging:
  level:
    com.jack.outboxservice: INFO  # Adjusted for outbox-service

  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"
