openapi:
  title: "Outbox Service API"
  version: "v1"

spring:
  rabbitmq:
    host: rabbitmq  # RabbitMQ host in Docker environment
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://db:5432/outboxdb  # Docker database connection for outbox messages
    username: postgres
    password: Ab123456
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true  # Outbox pattern requires auto-commit for message persistence

  jpa:
    hibernate:
      ddl-auto: update  # Automatically create/update tables in the database
    show-sql: true  # For debugging, shows SQL statements in the log
    open-in-view: false  # Disable Open Session in View for better performance

app:
  wallet:
    cache-prefix: "walletBalance:"  # Redis key prefix for wallet balances
    reply-to-queue: user-service.response.queue  # Reply queue for responses
    queue:
      create: wallet.create.queue      # Queue for wallet creation messages
      update: wallet.update.queue      # Queue for wallet update messages
      balance: wallet.balance.queue    # Queue for wallet balance requests
    exchange: wallet-exchange          # Exchange for wallet messages
    routing-key:
      create: wallet.creation          # Routing key for wallet creation
      update: wallet.update          # Routing key for wallet update
      balance: wallet.balance          # Routing key for wallet balance requests

# SpringDoc settings for API documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging pattern
logging:
  level:
    com.jack.outboxservice: INFO  # Adjusted for outbox-service

  pattern:
    console: "${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}"
