spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

openapi:
  title: User Management API
  version: v1.0
  description: This API provides user management functions for applications.
  termsOfService: https://test.com/terms
  contact:
    name: Jack Lee
    email: jack@test.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
